Remove realsence support due to it not being used and also due to a bug in the library.
Here is a sample of the error:
/root/movo_ws/src/movo_common/movo_third_party/realsense2_camera/src/base_realsense_node.cpp:1394:1:   required from here
/opt/ros/kinetic/include/librealsense2/hpp/rs_frame.hpp:1131:13: error: no match for call to ‘(rs2::asynchronous_syncer) (rs2::frame)’
             on_frame_function(frame{ fref });
             ^